/**
 * BreadWallet
 *
 * Created by Pablo Budelli <pablo.budelli@breadwallet.com> on 10/17/19.
 * Copyright (c) 2021 Breadwinner AG
 *
 * SPDX-License-Identifier: BUSL-1.1
 */
package com.breadwallet.ui.settings

enum class SettingsOption {
    // HOME
    SCAN_QR,
    PREFERENCES,
    SECURITY_SETTINGS,
    SUPPORT,
    SUBMIT_REVIEW,
    REWARDS,
    ABOUT,
    ATM_FINDER,
    EXPORT_TRANSACTIONS,
    DEVELOPER_OPTIONS,

    // PREFERENCES
    CURRENCY,
    BTC_MENU,
    BCH_MENU,
    SHARE_ANONYMOUS_DATA,
    RESET_DEFAULT_CURRENCIES,
    NOTIFICATIONS,

    // SECURITY SETTINGS
    FINGERPRINT_AUTH,
    UPDATE_PIN,
    PAPER_KEY,
    WIPE,

    // DEVELOPER OPTIONS
    SEND_LOGS,
    API_SERVER,
    ONBOARDING_FLOW,
    WEB_PLAT_DEBUG_URL,
    WEB_PLAT_BUNDLE,
    TOKEN_BUNDLE,
    NATIVE_API_EXPLORER,
    WIPE_NO_PROMPT,
    ENABLE_ALL_WALLETS,
    TOGGLE_RATE_APP_PROMPT,
    VIEW_LOGS,
    COPY_PAPER_KEY,
    METADATA_VIEWER,

    // BTC
    REDEEM_PRIVATE_KEY,
    SYNC_BLOCKCHAIN_BTC,
    SYNC_BLOCKCHAIN_BCH,
    BTC_NODES,
    ENABLE_SEG_WIT,
    VIEW_LEGACY_ADDRESS,
    FAST_SYNC_BTC,
    // Hidden
    CLEAR_BLOCKCHAIN_DATA,
    REFRESH_TOKENS,
    DETAILED_LOGGING,
}

